# Autogenerated. Do not edit. 

set(arduinolibs_ArduinoCore-samd Adafruit_ZeroDMA;EnergySaving;FlashStorage;HID;I2S;LoRaWan;SPI;Seeed_Arduino_FreeRTOS;Seeed_Arduino_LCD;SoftwareSerial;TimerTC3;TimerTCC0;USBHost;Wire)

set(arduinolib_Adafruit_ZeroDMA_srcs
    ArduinoCore-samd/libraries/Adafruit_ZeroDMA/Adafruit_ZeroDMA.cpp
)

set(arduinolib_Adafruit_ZeroDMA_incs
    ArduinoCore-samd/libraries/Adafruit_ZeroDMA
)

set(arduinolib_EnergySaving_srcs
    ArduinoCore-samd/libraries/EnergySaving/src/EnergySaving.cpp
)

set(arduinolib_EnergySaving_incs
    ArduinoCore-samd/libraries/EnergySaving/src
)

set(arduinolib_FlashStorage_srcs
    ArduinoCore-samd/libraries/FlashStorage/src/FlashStorage.cpp
)

set(arduinolib_FlashStorage_incs
    ArduinoCore-samd/libraries/FlashStorage/src
)

set(arduinolib_HID_srcs
    ArduinoCore-samd/libraries/HID/HID.cpp
)

set(arduinolib_HID_incs
    ArduinoCore-samd/libraries/HID
)

set(arduinolib_I2S_srcs
    ArduinoCore-samd/libraries/I2S/src/I2S.cpp
    ArduinoCore-samd/libraries/I2S/src/utility/DMA.cpp
    ArduinoCore-samd/libraries/I2S/src/utility/I2SDoubleBuffer.cpp
)

set(arduinolib_I2S_incs
    ArduinoCore-samd/libraries/I2S/src
)

set(arduinolib_LoRaWan_srcs
    ArduinoCore-samd/libraries/LoRaWan/LoRaWan.cpp
)

set(arduinolib_LoRaWan_incs
    ArduinoCore-samd/libraries/LoRaWan
)

set(arduinolib_SPI_srcs
    ArduinoCore-samd/libraries/SPI/SPI.cpp
)

set(arduinolib_SPI_incs
    ArduinoCore-samd/libraries/SPI
)

set(arduinolib_Seeed_Arduino_FreeRTOS_srcs
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/boards/SAMD21/FreeRTOSVariant.cpp
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/boards/SAMD51/FreeRTOSVariant.cpp
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/croutine.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/event_groups.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/heap_4.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/list.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/port.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/queue.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/stream_buffer.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/tasks.c
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src/timers.c
)

set(arduinolib_Seeed_Arduino_FreeRTOS_incs
    ArduinoCore-samd/libraries/Seeed_Arduino_FreeRTOS/src
)

set(arduinolib_Seeed_Arduino_LCD_srcs
    ArduinoCore-samd/libraries/Seeed_Arduino_LCD/TFT_Interface.cpp
    ArduinoCore-samd/libraries/Seeed_Arduino_LCD/TFT_eSPI.cpp
)

set(arduinolib_Seeed_Arduino_LCD_incs
    ArduinoCore-samd/libraries/Seeed_Arduino_LCD
)

set(arduinolib_SoftwareSerial_srcs
    ArduinoCore-samd/libraries/SoftwareSerial/SoftwareSerial.cpp
)

set(arduinolib_SoftwareSerial_incs
    ArduinoCore-samd/libraries/SoftwareSerial
)

set(arduinolib_TimerTC3_srcs
    ArduinoCore-samd/libraries/TimerTC3/TimerTC3.cpp
)

set(arduinolib_TimerTC3_incs
    ArduinoCore-samd/libraries/TimerTC3
)

set(arduinolib_TimerTCC0_srcs
    ArduinoCore-samd/libraries/TimerTCC0/TimerTCC0.cpp
)

set(arduinolib_TimerTCC0_incs
    ArduinoCore-samd/libraries/TimerTCC0
)

set(arduinolib_USBHost_srcs
    ArduinoCore-samd/libraries/USBHost/src/KeyboardController.cpp
    ArduinoCore-samd/libraries/USBHost/src/MouseController.cpp
    ArduinoCore-samd/libraries/USBHost/src/Usb.cpp
    ArduinoCore-samd/libraries/USBHost/src/adk.cpp
    ArduinoCore-samd/libraries/USBHost/src/hid.cpp
    ArduinoCore-samd/libraries/USBHost/src/hidboot.cpp
    ArduinoCore-samd/libraries/USBHost/src/hidescriptorparser.cpp
    ArduinoCore-samd/libraries/USBHost/src/hiduniversal.cpp
    ArduinoCore-samd/libraries/USBHost/src/message.cpp
    ArduinoCore-samd/libraries/USBHost/src/parsetools.cpp
    ArduinoCore-samd/libraries/USBHost/src/usbhub.cpp
)

set(arduinolib_USBHost_incs
    ArduinoCore-samd/libraries/USBHost/src
)

set(arduinolib_Wire_srcs
    ArduinoCore-samd/libraries/Wire/Wire.cpp
)

set(arduinolib_Wire_incs
    ArduinoCore-samd/libraries/Wire
)

